export const LOGIN = '/login'
export const GITHUBLOGIN = '/github-login'
export const SIGN_UP = '/sign-up'
export const TRANSACTION = '/transaction'
export const CATEGORY = '/category'
export const PAYMENT = '/payment'
